name: Manual deployment
on: 
  workflow_dispatch:
    inputs:
      release:
        description: 'Which github code release to push to production'
        required: true 
        type: release

env:
  APP_NAME: test-deployments-application

jobs:
  deploy_package: 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: ${{ env.APP_NAME }}-production
          version_label: ${{ env.APP_NAME }}-${{ github.event.inputs.release }}
          region: ${{ secrets.AWS_REGION }}
          wait_for_deployment: false