name: Manual deployment
on: 
  workflow_dispatch:

env:
  APP_NAME: test-deployments-application

jobs:
  deploy_package: 
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Trigger elastic beanstalk deployment
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ env.APP_NAME }}-production \
          --version-label "${{ env.APP_NAME }}-$GITHUB_REF_NAME"