name: Auto Version
on:
  workflow_run:
    workflows: ["Lint & Test"]
    types: completed
    branches: ["master"]

jobs:
  auto_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.0.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'feat'
          major-wording: 'major'
          patch-wording: 'fix'
          commit-message: '[skip ci] Increment version to {{version}}'